### ISSUE TITLE
Adding additional JavaScript to footer

### ISSUE THREAD

**Issue by k0nsl** [jberger/Galileo#54]
If I wish to add additional JavaScript to the footer, what's the easiest route to do so?

I assumed it would be to edit one of the following files:
```
root@illy:~/.cpan/build/Galileo-0.042-Zo7S1B/lib/Galileo/files/templates# cd layouts
root@illy:~/.cpan/build/Galileo-0.042-Zo7S1B/lib/Galileo/files/templates/layouts# ls
basic.html.ep  standard.html.ep
```
However, when I edit either of them (making sure I send a `SIGHUP` to Galileo after each edit) there is no change -- despite what I add.

Any ideas or recommendations?

**Comment by jberger** [comment]
Those are the build directories from cpanm and (probably) aren't the files
that are actually being used. Additionally, I don't think the Mojo servers
respond to SIGHUP.

I did add a small feature to Galileo at one point to allow adding
javascript to the standard template via a key "extra_js" =>
['path/to/file', ...] but it seems I didn't document it :(
https://metacpan.org/source/JBERGER/Galileo-0.042/lib/Galileo/files/templates/header_common.html.ep
Also
it only ads it to the end of the head tag and not the body. I would accept
a PR to do the latter (and document it) if you were so inclined.

I don't put much time into Galileo anymore, I have some plans for a second
CMS but who has the time right :-P

**Comment by k0nsl** [comment]
Aha, I see! And sorry to hear about you having practically no time for this project. I found a year or so ago and just never got around to use it, but now I did and I quite like it. It is simple and to the point, that's what I like in some cases. It just does what it is supposed to do! And written in perl, which is powerful, well, that is rather interesting too!

**Comment by jberger** [comment]
I have gotten much busier since I wrote this and so time is hard to come by. I also think that some of my design decisions constrain it where it might have been easier. I don't especially want to see it stagnate. I'd accept PRs if people give them, but if I found a chunk of time I'd probably put it toward another attempt at a CMS.

I'm glad that the simplicity and "to the point"ed-ness was a selling point for you. That was indeed one of the goals. My next one would still have those goals but I think I would probably require Postgres rather than trying to stay DB agnostic.
